ALTER TYPE "TipoObra" ADD VALUE IF NOT EXISTS 'PAVIMENTACAO';
ALTER TYPE "TipoObra" ADD VALUE IF NOT EXISTS 'TERRAPLENAGEM';
ALTER TYPE "TipoObra" ADD VALUE IF NOT EXISTS 'OBRA_ARTE';
ALTER TYPE "TipoObra" ADD VALUE IF NOT EXISTS 'DRENAGEM';
ALTER TYPE "TipoObra" ADD VALUE IF NOT EXISTS 'NAO_PREDIAL';
ALTER TABLE "simulacoes" ADD COLUMN "areaDemolicao" DOUBLE PRECISION NOT NULL DEFAULT 0;
